### ISSUE TITLE
The font is so hard to read I wish I was blind

### ISSUE THREAD

**Issue by AlexDaniel** [tony-o/perl-zefserver#2]
Maybe there is some configuration issue. That's how I see it:
![screenshot](https://files.progarm.org/2016-10-16-201559_972x613_scrot.png)

If that's how it is supposed to be, then please consider using a font that has more weight. Trying to read this causes physical pain for me.

Another way to improve the situation is to use black font color. This makes a huge difference, but it is still not enough.

**Comment by tony-o** [comment]
Updated the font for something heavier.  Looks like you're using Ubuntu or something with a windows like font renderer

**Comment by AlexDaniel** [comment]
O, yeah! **Much** better now! Thank you!

I am on debian unstable. The screenshot was taken in firefox (45.4.0). FWIW, freetype version is 2.6.3 (not 2.7), but I am not sure if that is relevant.
