### ISSUE TITLE
repo browser doesn't escape < > in source display

### ISSUE THREAD

**Issue by timo** [tony-o/perl-zefserver#3]
Here's an example where half way through the source file a <ARGB8888> tag opens and makes the rest of the source file have proportional font:

http://modules.zef.pm/modules/Timo%20Paulssen/SDL2::Raw?file=examples/shooter.pl#source

**Comment by tony-o** [comment]
This should also be correct, please verify -

**Comment by timo** [comment]
yup, that stuff works now! thanks
