### ISSUE TITLE
should relative paths in README (like images) work?

### ISSUE THREAD

**Issue by timo** [tony-o/perl-zefserver#4]
Here's an example where screenshots embedded with relative paths in README.md are broken in the documentation:

http://modules.zef.pm/modules/Timo%20Paulssen/SDL2::Raw#documentation

Maybe the path should be translated?

**Comment by tony-o** [comment]
They don't work right now, I'll take a look at how to make this work better -

**Comment by tony-o** [comment]
They should work now, if this (and the other two bugs filed) look good let me know and I'll close the tickets -

**Comment by timo** [comment]
looks good to me, thanks!
